name: CI-Polaris-Basic 
on:
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Polaris Scan
        uses: synopsys-sig/synopsys-action@SIGINT-2052
        with:
          ### SCANNING: Required fields
          polaris_server_url: ${{ secrets.POLARIS_SERVER_URL }}
          polaris_access_token: ${{ secrets.POLARIS_ACCESS_TOKEN }}
          polaris_assessment_types: "SCA,SAST"
          
          ### SCANNING: Optional fields
          polaris_application_name: "E2E-Integration-App"
          polaris_project_name: "TestProject"
          
          ### PULL REQUEST COMMENTS: Uncomment below to enable
          # polaris_prComment_enabled: true 
          github_token: ${{ secrets.GITHUB_TOKEN }} # Required when PR comments is enabled

          ### SARIF report parameters
          polaris_reports_sarif_create: true
          # polaris_reports_sarif_file_path: ""
          # polaris_reports_sarif_severities: "critical,high,medium,low"
          polaris_reports_sarif_groupSCAIssues: true
          # polaris_reports_sarif_issue_types: 'SCA'
          # polaris_upload_sarif_report: true
